language: python
python:
- '3.6'
services:
- docker
install:
- pip install websocket-client
script:
- python -m unittest discover
- mkdir report
- python autobahn-test.py &
- docker run -it -v $(pwd)/report:/autobahn-python-master/wstest/reports/servers --network="host" haegi/autobahn-testsuite make test_server
env:
  global:
    secure: UighEOqhh/ye4cCKWevw0tRhSX67tUsS65qlczkOOlpeg4rs5nS8sRjDf1ilsAUe3Xc4jpxon86nreLa0NYZM29QOS2egt5zRymz/QHJ2RdiTCK2J0Z2i9KF3RKb/vhvnjYPFba83UeNKrd9t0JNf4p3JNbWcdX3GZX1lnhw95V0mVwZgTTN15Hguz6WA3USHETm+FnUiQDcSrSKFdQl6peq5rS4xWRg7TxR/Z8cf1b75lk6vW0fE1oRpTKfIYD/D0E+S+64PfJAtLLXhnmhaoSSRXdTx0OMWuDM6XNgOxICTF3ETkhRzDiIfQUSeop+L+RVpcoj0xKeKc/y3vzes3md+YZ5jJtJ82pGqOoXbSmcQkwl1ImGffnYoX4Qf+NDGIXgq4nn7Go6v+VReZ76ZQFIKy+sRh9jmyI3ZyRpSGD0410S6Vb1m6gla+FhfnTGKekQElqbRtix3kPxuHvU6T0fPhWqrG+Kc4CcurkXdKkAd3usMwKuM+G3OEcvrjONwQmaAwHHykCPKLseBcw74hOhoAi+O03+bDK03ftMMIwV7HfuQgXrwIoBhsXhJ/hQbfGg3wriH7nyVFDwiM0RhHOgoc5VtTZppXmyMiUku6UuiFaOht0n7kr8ou6xI6Vl40PhsZMpJRbjXZVwn4AIIo3walhzGQH1OpguXHPjBMQ=
deploy:
- provider: script
  script:
      - chmod 0700 ./push.sh
      - cd report
      - "./../push.sh"
  on:
    branch: dev
- provider: pypi
  user: "Kai-Bailey"
  password:
    secure: guSyRyd7L71uvzTFvbjZXFGJZH2wW4hFT2bD54oq31zkhbpd1sxBXayk9Po/ygQV48EUEdvgMcUTFLwtkAC/eS3FDygdfnLV6Evm0F7HupUUWeH9+Apw/rN3f6o9CkQ98L95Zy6kXibZZevUhllPClYuY8IShYAoGQtql4wgh1YfUtwvyC+r3AjTOKaxY7NCLOOj8ACIWDXGEPuocvSUwKN8S+UoOApTRN+Qx50suN/9JXLdRBRT9Izh2G0r8EGbpumqvP8hkNGEOj/5TEwxJyVmgq/UZOypv/x8BxS+SAkbnNwzVwVG1wDVXHYkLgbX8SSPiq8JYLjDaAIkhw4OGZ8eSJZPSkvPYehms7rbBBX7e9wMt9KmrbXNNa1fUw3FRDiUII/qDzA0ze7vNRcGoim9xn4jwaRTScOopH1eXN8VgUpXBhdKlb2Sbm6Z2dEFyTqwdbCL9XGdzqRve+rcW9fMR8d343+Fk7Fp1btSh3I6fcXtbjHGygv9t45ioAiwN7RjVB431khqr/lVMsY/YCfoqCqc9wqlFDheI7VNHXbDzk6mKb6ie0F3QEoCCMwKeDtRrtT7Re5I/PauBKSzjjwuN3602jBP9FjKNTNiFTSq+bvFeKj6Pp8nSKRIVxGGPO+wbkPEmtb6JanU4X+4uYlnNlZCPZL+Optco4v0QNk=
